### ISSUE TITLE
SoapUI download link and environments

### ISSUE THREAD

**Issue by ygeelen-tb** [tomap/soapui-extensions#1]
The download link that's embedded in the task is dead: http://cdn01.downloads.smartbear.com/soapui/5.3.0/SoapUI-5.3.0-windows-bin.zip

Could you fix this and perhaps also foresee a task parameter to overrride de URL to download from?
Strangely even if we install SoapUI on our build server, the task still attempts to download SoapUI?

How should we deal with multiple URL's per environment when testing API's? Can we use the "P" argument for specifying them?

**Comment by tomap** [comment]
Thank you for noticing. I am mainly using it on hosted agents where the download only occurs once.
I could not find a url for 5.3 so I'll use the url for 5.4:
https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-windows-bin.zip

If you are also using hosted agent, you can grab a 5.4 zip and unzip it to the proper diretory (check the powershell script to understand)

As for your question about alternate url, could you send a PR? It's powershell only, it should be fairly easy to add

For your other question about supplying multiple urls, I have no clue (never needed that). You can test the testrunner command line and if you find how, please do submit either a PR or an howto on the command line so I can adapt the PS to do that

**Comment by ygeelen-tb** [comment]
We're using a private agent.
I also saw that the version number is used somewhere else in the code of the task so that would break: $soapUiExe = $path + "\soapui\SoapUI-5.3.0\bin\testrunner.bat"

I was referring to this parameter:
https://www.soapui.org/test-automation/running-functional-tests.html
"P : Sets project property with name=value, e.g. -Pendpoint=Value1 -PsomeOtherProperty=value2"

I'm currently not working on the project where they need this, so someone else will likely pick this up in the near future.

**Comment by ygeelen-tb** [comment]
Why not simply include testrunner.bat in your sources and skip downloading and extracting the installer?
Is it dependent on other installation files?

**Comment by tomap** [comment]
Because you need about 46Mb to have a working soapui (all the jars) and last I checked, there was a 20Mb limit for VSTS Extensions :(
(It's not just the .bat file)

**Comment by ygeelen-tb** [comment]
Alright that's what I feared.. Good to know about that size limit.

**Comment by ygeelen-tb** [comment]
FYI the working URL is https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-windows-bin.zip and the unzipped folder name is SoapUI-5.4.0 (occurs in both tasks).
