### ISSUE TITLE
Could you please update the jars 

### ISSUE THREAD

**Issue by AjeetChouksey-zz** [tomap/soapui-extensions#3]
HI Tom,

There are few external jars which are required by framework to support input, detailed and consolidated report.

1. POI.jar (Apache POI to generate consolidated report), 
2. jxl.jar (to fetch data at runtime from input xls) and
3.  SQLJDBC42.jar (to establish connection to Azure SQL DB for validations).
 These jars doesn’t come as part of standard sopaui jars and needs to be added externally at soapui installation folder at bin/ext and jre 

1. SoapUI-5.4.0\bin\ext - poi-3.16, sqljdbc_auth, sqljdbc42
2. SoapUI-5.4.0\jre\lib - sqljdbc42
3. Program Files\SmartBear\SoapUI-5.4.0\lib – jxl 

Could you please add these jar files in SOAP UI .zip
[jars.zip](https://github.com/tomap/soapui-extensions/files/1987676/jars.zip)

**Comment by tomap** [comment]
Hi,

I'll look at that by the end of the month.

If you want to speed up the process, I'll gladly accept a PR.

And if you could also add a link about where you download those, it would be better

Thank you

**Comment by AjeetChouksey-zz** [comment]
Thanks Tom,

I will do the PR. Will also share the link for files, have to check with automation team from where they have downloaded.

**Comment by AjeetChouksey-zz** [comment]
Hi Tom,

PR is in place, could you please have a look and do the needful.

**Comment by AjeetChouksey-zz** [comment]
gentle reminder :)

**Comment by tomap** [comment]
Please see my readme:
Looking for someone to maintain this project
Hi, I'm looking for someone to take over this project as I no longer have time to dedicate to it.

If you would like to do so, please contact me via an issue, make a fork and do your first change. I can indicate on this README who is maintaining the project (name & url).
